name: StreamX Deployment

on:
  push:
    branches:
      - main
      - master
     

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy with Docker Compose
        run: |
          export DOCKER_BUILDKIT=0
          export COMPOSE_DOCKER_CLI_BUILD=0
          docker compose down || true
          docker compose build --no-cache
          docker compose up -d
          docker compose ps